package Enumerations;

//DO NOT USE RANDOM! THIS IS FOR THE XML PARSER ONLY

public enum States {
    ALIVE, DEAD, X, O, EMPTY, TREE, BURNING, SHARK, FISH, WATER, ROCK, PAPER, SCISSOR, RANDOM, FOOD, NEST, ANT_WITHOUT_FOOD, ANT_WITH_FOOD, PATCH, AGENT
}

